spring.application.name=Proyecto-Final

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/proyectofinaldb
spring.datasource.username=root
spring.datasource.password=prueba123
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=31536000
spring.web.resources.chain.cache=true
spring.web.resources.chain.enabled=true
spring.mvc.static-path-pattern=/static/**